/*
 RPi SID synth defines
*/

#define SID_OSC1_FREQ_LO 0
#define SID_OSC1_FREQ_HI 1
#define SID_OSC1_PW_LO 2
#define SID_OSC1_PW_HI 3
#define SID_OSC1_CTRL 4
#define SID_OSC1_ATTACK 5
#define SID_OSC1_SUSTAIN 6

#define SID_OSC2_FREQ_LO 7
#define SID_OSC2_FREQ_HI 8
#define SID_OSC2_PW_LO 9
#define SID_OSC2_PW_HI 10
#define SID_OSC2_CTRL 11
#define SID_OSC2_ATTACK 12
#define SID_OSC2_SUSTAIN 13

#define SID_OSC3_FREQ_LO 14
#define SID_OSC3_FREQ_HI 15
#define SID_OSC3_PW_LO 16
#define SID_OSC3_PW_HI 17
#define SID_OSC3_CTRL 18
#define SID_OSC3_ATTACK 19
#define SID_OSC3_SUSTAIN 20

#define SID_FLT_CUTOFF_LO 21
#define SID_FLT_CUTOFF_HI 22
#define SID_FLT_RESO_ROUTE 23
#define SID_FLT_MODE_VOL 24

#define SID_POTX 25
#define SID_POTY 26
#define SID_OSC3 27
#define SID_ENV3 28

/* virtual SID registers needed for patch manipulation rather than direct chip manipulation  */

#define SID_OSC1_STATE 32
#define SID_OSC1_DETUNE 33

#define SID_OSC2_STATE 64
#define SID_OSC2_DETUNE 65

#define SID_OSC3_STATE 96
#define SID_OSC3_DETUNE 97

#define QSID_OCTAVE_TRANSPOSITION 128

#define QSID_LFO1_RATE 130
#define QSID_LFO1_SHAPE 131
#define QSID_LFO1_DEPTH 132
#define QSID_LFO1_ROUTE 133

#define QSID_LFO2_RATE 140
#define QSID_LFO2_SHAPE 141
#define QSID_LFO2_DEPTH 142
#define QSID_LFO2_ROUTE 143

#define QSID_FILTER_ADSR_ATTACK 150
#define QSID_FILTER_ADSR_DECAY 152
#define QSID_FILTER_ADSR_SUSTAIN 153
#define QSID_FILTER_ADSR_RELEASE 154



