#define LFO_BASE_TICK 1000

#define LFO_OFF 0

#define LFO_ROUTING_CUTOFF 1
#define LFO_ROUTING_PW_1 2
#define LFO_ROUTING_PW_2 3
#define LFO_ROUTING_PW_3 4
#define LFO_ROUTING_PW_ALL 5
#define LFO_ROUTING_DETUNE_1 6
#define LFO_ROUTING_DETUNE_2 7
#define LFO_ROUTING_DETUNE_3 8
#define LFO_ROUTING_DETUNE_ALL 9
#define LFO_ROUTING_MAIN_VOLUME 10

#define LFO_SHAPE_TRIANGLE 11
#define LFO_SHAPE_SAWTOOTH 12
#define LFO_SHAPE_SQUARE 13
#define LFO_SHAPE_SH 14

#define LFO_RATE_MAX 100
#define LFO_DEPTH_MAX 100

#define LFO_RANGE 1024

void SYNTH_LFO1(void);

